import type { Metadata } from "next";

import {
  ClerkProvider,
  SignedOut,
  SignedIn,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
// import { ThemeToggle } from "../components/ThemeToggle";
import "./globals.css";
import ConvexClientProvider from "./ConvexClientProvider";
import { ThemeToggle } from "@/components/ThemeToggle";
import { SidebarWrapper } from "@/components/app-sidebar/sidebar-wrapper";
import { preloadQuery } from "convex/nextjs";
import { api } from "../../convex/_generated/api";
import localFont from "next/font/local";
import { UserConfigProvider } from "@/providers/user-config-provider";
import { TopBar } from "@/components/top-bar";

const proxima_var = localFont({
  src: "./proxima_vara.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const preloadedThreads = await preloadQuery(api.threads.getForCurrentUser);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${proxima_var.className} antialiased`}>
        <ClerkProvider>
          <ConvexClientProvider>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserConfigProvider>
                  <SidebarWrapper preloadedThreads={preloadedThreads}>
                    <main className="firefox-scrollbar-margin-fix min-h-pwa relative flex w-full flex-1 flex-col overflow-hidden transition-[width,height]">
                      <TopBar />
                      {children}
                    </main>
                  </SidebarWrapper>
                </UserConfigProvider>
              </SignedIn>
              <ThemeToggle />
            </ThemeProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
